### ISSUE TITLE
Issues on Docker build with snips tools

### ISSUE THREAD

**Issue by jhoelzl** [stiller-leser/snips-docker-pulseaudio#3]
Hello,

i have issues when i run `./build_image.sh` on line 9 whe installing the snips tools:

> Err:8 https://debian.snips.ai/bionic stable Release
>   404  Not Found [IP: 54.230.202.128 443]
> Reading package lists...
> E: The repository 'https://debian.snips.ai/bionic stable Release' does not have a Release file.
> The command '/bin/sh -c echo "deb https://debian.snips.ai/$(lsb_release -cs) stable main" > /etc/apt/sources.list.d/snips.list     && apt-key adv --keyserver  keyserver.ubuntu.com --recv-keys F727C778CCB0A455     && apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install --yes sudo unzip systemd pulseaudio-utils openssh-server alsa-utils nano curl unzip python-pip git snips-platform-voice snips-tts snips-template snips-skill-server snips-watch' returned a non-zero code: 100

They can not be download. Any suggestions?
Thanks!

Regards,
Josef

**Comment by stiller-leser** [comment]
Hey,

I haven't had time to play around with this. A quick look at the documentation showed that they changed the installation (https://docs.snips.ai/articles/raspberrypi/manual-setup). Try replacing the instructions here: https://github.com/stiller-leser/snips-docker-pulseaudio/blob/master/Dockerfile#L6 with the ones given in the article.

I'll try having a look at it later.

Best regards,
stiller-leser

**Comment by jhoelzl** [comment]
Thanks, i created a pull request for this: #4
